# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1201, 399)
        Form.setStyleSheet("backgrpund-color:rgb(255, 170, 255)")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 51))
        self.widget.setStyleSheet("background-color:rgb(0, 85, 255);\n"
"border-bottom-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(20, 70, 201, 201))
        self.widget_2.setStyleSheet("border-top-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;\n"
"border-image: url(:/images/biz.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(260, 70, 201, 201))
        self.widget_5.setStyleSheet("border-top-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;\n"
"border-image: url(:/images/image1.jpg);")
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(500, 70, 201, 201))
        self.widget_6.setStyleSheet("border-image: url(:/images/sign.jpg);\n"
"border-top-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;")
        self.widget_6.setObjectName("widget_6")
        self.widget_7 = QtWidgets.QWidget(Form)
        self.widget_7.setGeometry(QtCore.QRect(740, 70, 201, 201))
        self.widget_7.setStyleSheet("border-image: url(:/images/image2.jpg);\n"
"border-top-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;")
        self.widget_7.setObjectName("widget_7")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(980, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("border: 1px solid #ccc;\n"
"float: right;\n"
"padding: 6px;\n"
"border: none;\n"
"margin-top: 1px;\n"
"margin-right: 16px;\n"
"font-size: 10px;")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(990, 170, 171, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setTabletTracking(True)
        self.pushButton.setStyleSheet("border-top-left-radius:25px;\n"
"border-bottom-left-radius:25px;\n"
"border-top-right-radius:25px;\n"
"border-bottom-right-radius:25px;\n"
"background-color: #03dbfc\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.Name = QtWidgets.QLabel(Form)
        self.Name.setGeometry(QtCore.QRect(40, 340, 41, 31))
        self.Name.setStyleSheet(" font-size: 12px;\n"
" text-transform: uppercase;")
        self.Name.setObjectName("Name")
        self.Name_disp = QtWidgets.QLabel(Form)
        self.Name_disp.setGeometry(QtCore.QRect(80, 340, 271, 31))
        self.Name_disp.setStyleSheet(" font-size: 12px;\n"
" text-transform: uppercase;")
        self.Name_disp.setText("")
        self.Name_disp.setObjectName("Name_disp")
        self.address = QtWidgets.QLabel(Form)
        self.address.setGeometry(QtCore.QRect(470, 340, 61, 31))
        self.address.setStyleSheet(" font-size: 12px;\n"
" text-transform: uppercase;")
        self.address.setObjectName("address")
        self.address_disp = QtWidgets.QLabel(Form)
        self.address_disp.setGeometry(QtCore.QRect(540, 340, 401, 31))
        self.address_disp.setStyleSheet(" font-size: 12px;\n"
" text-transform: uppercase;")
        self.address_disp.setText("")
        self.address_disp.setObjectName("address_disp")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 280, 201, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-top-left-radius:25px;\n"
"border-bottom-left-radius:25px;\n"
"border-top-right-radius:25px;\n"
"border-bottom-right-radius:25px;\n"
"background-color: #038cfc;\n"
"color:white\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 280, 201, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-top-left-radius:25px;\n"
"border-bottom-left-radius:25px;\n"
"border-top-right-radius:25px;\n"
"border-bottom-right-radius:25px;\n"
"background-color: #038cfc;\n"
"color:white\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 280, 201, 51))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("border-top-left-radius:25px;\n"
"border-bottom-left-radius:25px;\n"
"border-top-right-radius:25px;\n"
"border-bottom-right-radius:25px;\n"
"background-color: #038cfc;\n"
"color:white\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(740, 280, 201, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("border-top-left-radius:25px;\n"
"border-bottom-left-radius:25px;\n"
"border-top-right-radius:25px;\n"
"border-bottom-right-radius:25px;\n"
"background-color: #038cfc;\n"
"color:white\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TOKIĆ"))
        self.lineEdit.setPlaceholderText(_translate("Form", "                         OIB"))
        self.pushButton.setText(_translate("Form", "Get Info"))
        self.Name.setText(_translate("Form", "Name:"))
        self.address.setText(_translate("Form", "ADDRESS:"))
        self.pushButton_2.setText(_translate("Form", "Get Patnership agreement"))
        self.pushButton_3.setText(_translate("Form", "Get Nondisclosure agreement"))
        self.pushButton_4.setText(_translate("Form", "Get Indemnity agreement"))
        self.pushButton_5.setText(_translate("Form", "Get Employment Contract"))

if __name__=='__main__':
    app=QtWidgets.QApplication(sys.argv)
    Form=QtWidgets.QWidget()
    ui=Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


